"use client";
import Layout from "@/components/layout/Layout";

export default function Yarn() {

  const backgroundImage = "/assets/images/kprmill-images/Products/ethanol/ethonal-banner.jpg";
  return (
    <>
      <Layout headerStyle={2} footerStyle={2} breadcrumbTitle="Ethanol & Power" imageUrl= {backgroundImage}>
        <section className="dream-style-three p_relative">
          <div className="auto-container">
            {/* <div className="sec-title  mb_30 text-center">
              <span className="sub-title" style={{ color: "black" }}>
                ELEMENTUM TEMPUS
              </span>
              <h2>
              YARN
              </h2>
            </div> */}
            <div class="row clearfix">
              <div class="col-lg-6 col-md-12 col-sm-12 order-lg-2 content-column">
                <div className="content_block_two">
                  <div className="content-box p_relative d_block">
                    <div className="sec-title mb_5">
                      {/* <span className="sub-title">Reach Your Dream</span> */}
                      <h3>Ethanol & Power</h3>
                    </div>

                    <div className="text mb_25">
                        <ul className="about-list-style clearfix">
                            <li>K.P.R. Sugar Mill Limited is a Co-gen cum Sugar Mill with 90 Mega Watts power generation and 470 Kilo Litres of Ethanol extraction capacity per day.</li>
                            <li>KPR has installed Windmills at diverse, strategic locations in Tamil Nadu with a capacity of 61.92 MW Green power generation (66 Windmills). </li>
                            <li>We also produce 40 MW of electricity through solar power units with future plans to increase our solar energy production. </li>
                            <li>KPR is proud to exclaim that the captive power generated by us is consumed within all our factory premises.</li>
                        </ul>
                      
                    </div>
                    {/* <div className="text ">
                      <h5 style={{ fontWeight: "600", marginBottom: "5px" }}>
                      KPR is proud to exclaim that the captive power
                      generated by us is consumed within all our factory premises.
                      </h5>
                     
                    </div> */}
                  </div>
                </div>
              </div>
              <div class="col-lg-6 col-md-12 col-sm-12 order-lg-1 image-column">
                <div class="image-box pl-3">
                  <figure class="image">
                    <img src="/assets/images/kprmill-images/Products/ethanol/ethonal-img.png" alt="sugar" />
                  </figure>
                </div>
              </div>
            </div>
          </div>
        </section>

 
      </Layout>
    </>
  );
}
